name: o_popup_example
description: o_popup example app
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  o_popup:
    path: ../
  cupertino_icons: ^0.1.3

flutter:
  uses-material-design: true
