language: dart
dist: xenial
install:
  - git clone https://github.com/flutter/flutter.git -b dev
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache