name: o_popup
description: An overlaid content, which closes itself into opening place (on back button) or into the position where the pointer contacted the screen. It means, popup supports tap gesture.
version: 1.0.1
homepage: https://github.com/owczaro/o_popup
issue_tracker: https://github.com/owczaro/o_popup/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
